// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
const { invoke } = vi.hoisted(() => ({ invoke: vi.fn() }));
vi.mock("@tauri-apps/api/core", () => ({ invoke }));
vi.mock("@tauri-apps/api/event", () => ({ listen: vi.fn().mockResolvedValue(() => {}) }));
import DeepResearchView from "./DeepResearchView";
afterEach(() => { cleanup(); invoke.mockReset(); });
describe("DeepResearchView", () => {
  it("rejects an empty question without invoking start", async () => { invoke.mockResolvedValueOnce({ runs: [], warnings: [] }); render(<DeepResearchView />); await screen.findByText("No research reports yet"); fireEvent.click(screen.getByRole("button", { name: "Start research" })); expect(screen.getByRole("alert")).toHaveTextContent("Enter a research question"); expect(invoke).not.toHaveBeenCalledWith("start_deep_research", expect.anything()); });
  it("renders progress, partial output, sources, and resume", async () => { invoke.mockResolvedValueOnce({ warnings: [], runs: [{ version: 1, id: "one", query: "Question", state: "interrupted", generation: 2, created_at: 1, updated_at: 2, session_id: "research-one", progress: { phase: "reading", activity: "Reading sources", searches: 2, reads: 1, checks: 0, active_calls: [] }, partial_report: "# Partial", sources: [{ url: "https://example.com", canonical_url: "https://example.com", title: "Example", cited: false }], cancellation_requested: false, resume_count: 0 }] }); render(<DeepResearchView />); expect(await screen.findByRole("heading", { name: "Question" })).toBeInTheDocument(); expect(screen.getByText("Partial report")).toBeInTheDocument(); expect(screen.getByRole("link", { name: "Example" })).toHaveAttribute("rel", "noreferrer"); expect(screen.getByRole("button", { name: "Resume" })).toBeInTheDocument(); });
  it("confirms cancellation and explains partial retention", async () => { invoke.mockResolvedValueOnce({ warnings: [], runs: [{ version: 1, id: "one", query: "Question", state: "running", generation: 2, created_at: 1, updated_at: 2, session_id: "research-one", progress: { phase: "searching", activity: "Searching", searches: 0, reads: 0, checks: 0, active_calls: [] }, partial_report: "", sources: [], cancellation_requested: false, resume_count: 0 }] }); render(<DeepResearchView />); fireEvent.click(await screen.findByRole("button", { name: "Cancel" })); await waitFor(() => expect(screen.getByRole("alertdialog")).toHaveTextContent("partial report and source list remain")); });
  it("resumes the selected run using its stable run id", async () => { const interrupted = { version: 1, id: "one", query: "Question", state: "interrupted", generation: 2, created_at: 1, updated_at: 2, session_id: "research-one-resume-1", progress: { phase: "reading", activity: "Interrupted", searches: 1, reads: 1, checks: 0, active_calls: [] }, partial_report: "# Partial", sources: [], cancellation_requested: false, resume_count: 0 }; invoke.mockResolvedValueOnce({ warnings: [], runs: [interrupted] }).mockResolvedValueOnce({ ...interrupted, state: "running", resume_count: 1 }).mockResolvedValueOnce({ warnings: [], runs: [{ ...interrupted, state: "running", resume_count: 1 }] }); render(<DeepResearchView />); fireEvent.click(await screen.findByRole("button", { name: "Resume" })); await waitFor(() => expect(invoke).toHaveBeenCalledWith("resume_deep_research", { runId: "one" })); });
});
