import { useCallback, useEffect, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { open } from "@tauri-apps/plugin-dialog";
import { useModalFocus } from "./useModalFocus";
import { assetChecklist, canGenerateDocumentary, validateBrief, validateDocumentary, type DocumentaryBrief, type DocumentaryData, type DocumentaryPackage, type Scene } from "../lib/documentary";
import { isActiveResearch, type ResearchData, type ResearchRun } from "../lib/deep-research";

function DeleteDialog({ pkg, onClose, onConfirm }: { pkg: DocumentaryPackage; onClose: () => void; onConfirm: () => void }) {
  const ref = useModalFocus<HTMLDivElement>(onClose);
  return <div className="approval-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div ref={ref} className="approval-dialog" role="alertdialog" aria-modal="true" aria-labelledby="documentary-delete-title" tabIndex={-1}><header><small>Documentary</small><h2 id="documentary-delete-title">Delete “{pkg.topic}”?</h2></header><p className="approval-message">This deletes the local production package. Exported files remain untouched.</p><footer><button className="approval-cancel" onClick={onClose}>Keep package</button><button className="approval-submit" onClick={onConfirm}>Delete package</button></footer></div></div>;
}

function SceneEditor({ scene, onChange }: { scene: Scene; onChange: (scene: Scene) => void }) {
  const update = (field: keyof Scene, value: string) => onChange({ ...scene, [field]: value });
  return <article className="documentary-scene"><header><strong>Scene {scene.order}</strong><span>{scene.motionSuggestion.replace("_", " ")}</span></header><label>Voice-over<textarea value={scene.voiceover} onChange={(e) => update("voiceover", e.target.value)} /></label><label>On-screen text<textarea value={scene.onScreenText.join("\n")} onChange={(e) => onChange({ ...scene, onScreenText: e.target.value.split("\n").filter(Boolean) })} /></label><label>Visual concept<textarea value={scene.visualConcept} onChange={(e) => update("visualConcept", e.target.value)} /></label><small>{scene.emotionalBeat}</small></article>;
}

export default function DocumentaryView() {
  const [data, setData] = useState<DocumentaryData>({ packages: [], warnings: [] }); const [research, setResearch] = useState<ResearchData>({ runs: [], warnings: [] }); const [selected, setSelected] = useState<string | null>(null);
  const [brief, setBrief] = useState<DocumentaryBrief>({ topic: "", language: "English", audience: "", durationSeconds: 45 }); const [researchQuery, setResearchQuery] = useState(""); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [deleting, setDeleting] = useState<DocumentaryPackage | null>(null);
  const load = useCallback(async () => { try { const [next, researchData] = await Promise.all([invoke<DocumentaryData>("list_documentary_packages"), invoke<ResearchData>("get_deep_research_data")]); setData(next); setResearch(researchData); setSelected((id) => id && next.packages.some((pkg) => pkg.id === id) ? id : next.packages[0]?.id ?? null); setError(null); } catch (e) { setError(String(e)); } }, []);
  useEffect(() => { void load(); const unlistens = [listen("documentary-changed", () => void load()), listen("deep-research-changed", () => void load())]; return () => { void Promise.all(unlistens).then((listeners) => listeners.forEach((fn) => fn())); }; }, [load]);
  const current = data.packages.find((pkg) => pkg.id === selected) ?? data.packages[0];
  async function create(e: React.FormEvent) { e.preventDefault(); const errors = validateBrief(brief); if (errors.length) return setError(errors[0]); setBusy(true); try { const pkg = await invoke<DocumentaryPackage>("create_documentary_package", { input: brief }); setSelected(pkg.id); setBrief({ topic: "", language: "English", audience: "", durationSeconds: 45 }); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function save(pkg: DocumentaryPackage) { const errors = validateDocumentary(pkg); if (errors.length) return setError(errors[0]); setBusy(true); try { await invoke("update_documentary_package", { package: pkg }); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function approve(sourceId: string, approved: boolean) { if (!current) return; setBusy(true); try { await invoke("approve_documentary_source", { packageId: current.id, sourceId, approved }); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function startResearch(e: React.FormEvent) { e.preventDefault(); if (!current || !researchQuery.trim()) return setError("Enter a research question."); setBusy(true); try { await invoke<ResearchRun>("start_deep_research", { input: { query: researchQuery, model: null, provider: null, thinking: null, originChatId: null, originSessionId: null, documentaryPackageId: current.id } }); setResearchQuery(""); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function attachResearch(researchRunId: string) { if (!current) return; setBusy(true); try { await invoke("attach_documentary_research", { packageId: current.id, researchRunId }); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function generate() { if (!current) return; setBusy(true); try { await invoke("generate_documentary_package", { packageId: current.id }); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function exportPackage() { if (!current) return; const directory = await open({ directory: true, multiple: false }); if (!directory) return; setBusy(true); try { const output = await invoke<string>("export_documentary_package", { packageId: current.id, directory }); setSuccess(`Exported package to ${output}`); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  async function remove() { if (!deleting) return; setBusy(true); try { await invoke("delete_documentary_package", { packageId: deleting.id }); setDeleting(null); await load(); } catch (x) { setError(String(x)); } finally { setBusy(false); } }
  return <section className="documentary-view"><header className="documentary-header"><div><small>Global · Production package</small><h1>Documentary</h1><p>Research-grounded vertical reel briefs. Assets remain manual and licensed by you.</p></div><span>{data.packages.length} packages</span></header>
    <form className="documentary-brief" onSubmit={create}><strong>1. Create brief</strong><label>Topic<input value={brief.topic} onChange={(e) => setBrief({ ...brief, topic: e.target.value })} placeholder="What story are you telling?" /></label><label>Language<input value={brief.language} onChange={(e) => setBrief({ ...brief, language: e.target.value })} /></label><label>Audience<input value={brief.audience} onChange={(e) => setBrief({ ...brief, audience: e.target.value })} placeholder="Who is this for?" /></label><label>Duration<select value={brief.durationSeconds} onChange={(e) => setBrief({ ...brief, durationSeconds: Number(e.target.value) as 30 | 45 | 60 })}><option value={30}>30 seconds</option><option value={45}>45 seconds</option><option value={60}>60 seconds</option></select></label><button disabled={busy}>{busy ? "Working…" : "Create package"}</button></form>
    {error && <p className="kanban-error" role="alert">{error}</p>}{success && <p className="research-warning" role="status">{success}</p>}{data.warnings.map((warning) => <p className="research-warning" key={warning}>{warning}</p>)}
    {!current ? <div className="research-empty"><strong>No production packages yet</strong><span>Create a brief to start source review and storyboard work.</span></div> : <div className="documentary-layout"><nav aria-label="Documentary packages">{data.packages.map((pkg) => <button key={pkg.id} className={pkg.id === current.id ? "active" : ""} onClick={() => setSelected(pkg.id)}><strong>{pkg.topic}</strong><span>{pkg.state} · {pkg.durationSeconds}s</span></button>)}</nav><main className="documentary-detail"><header><div><span className="research-state">{current.state}</span><h2>{current.topic}</h2><small>{current.language} · {current.audience} · vertical {current.durationSeconds}s</small></div><div><button className="research-danger" onClick={() => setDeleting(current)} disabled={busy}>Delete</button><button onClick={() => void exportPackage()} disabled={busy}>Export package</button></div></header>
      <section className="documentary-step"><h3>2. Research and source approval</h3><form className="research-composer" onSubmit={startResearch}><label htmlFor="documentary-research-question">Research question</label><textarea id="documentary-research-question" value={researchQuery} onChange={(e) => setResearchQuery(e.target.value)} maxLength={10000} placeholder="What should Pi investigate across the web?" disabled={busy || research.runs.some(isActiveResearch)} /><div><span>{research.runs.some(isActiveResearch) ? "One run is already active." : "Only approved web tools are available."}</span><button disabled={busy || research.runs.some(isActiveResearch)}>{busy ? "Starting…" : "Start research"}</button></div></form>{research.runs.filter((run) => run.documentary_package_id === current.id && isActiveResearch(run)).length > 0 && <div className="documentary-research-runs">{research.runs.filter((run) => run.documentary_package_id === current.id && isActiveResearch(run)).map((run) => <article key={run.id}><strong>{run.query}</strong><span>{run.state} · research in progress</span></article>)}</div>}{research.runs.filter((run) => run.documentary_package_id === current.id && run.state === "completed" && !!run.final_report).length ? <div className="documentary-research-runs">{research.runs.filter((run) => run.documentary_package_id === current.id && run.state === "completed" && !!run.final_report).map((run) => <article key={run.id}><strong>{run.query}</strong><span>{run.sources.length} sources · {run.final_report!.length.toLocaleString()} character report</span><button onClick={() => void attachResearch(run.id)} disabled={busy || !run.sources.length || current.researchRunId === run.id}>{current.researchRunId === run.id ? "Attached" : "Attach"}</button></article>)}</div> : <p>No completed research reports available.</p>}{current.sources.length ? <ul className="documentary-sources">{current.sources.map((source) => <li key={source.id}><label><input type="checkbox" checked={source.approved} onChange={(e) => void approve(source.id, e.target.checked)} disabled={busy} /> Approve</label><a href={source.url} target="_blank" rel="noreferrer">{source.title || source.url}</a>{source.cited && <span>cited</span>}</li>)}</ul> : <p>No research attached. Add a completed Deep Research run before generation.</p>}</section>
      <section className="documentary-step"><h3>3. Script and storyboard</h3><p>{canGenerateDocumentary(current) ? "Approved evidence is ready for package generation." : "Approve at least one source before generation."}</p>{canGenerateDocumentary(current) && !current.script && <button onClick={() => void generate()} disabled={busy}>Generate package</button>}{current.script && <><label>Hook<textarea value={current.script.hook} onChange={(e) => void save({ ...current, script: { ...current.script!, hook: e.target.value } })} /></label><div className="documentary-claims">{current.script.claims.map((claim) => <p key={claim.id} className={claim.status}><strong>{claim.status}</strong> {claim.text} {claim.status === "verified" ? claim.sourceIds.map((id) => <span key={id}>source {id}</span>) : <em>Needs human verification.</em>}</p>)}</div></>}{current.scenes.map((scene, index) => <SceneEditor key={scene.id} scene={scene} onChange={(next) => void save({ ...current, scenes: current.scenes.map((item, i) => i === index ? next : item) })} />)}</section>
      <section className="documentary-step"><h3>4. Manual asset checklist</h3>{assetChecklist(current).map(({ scene, assets }) => <div className="documentary-assets" key={scene.id}><strong>Scene {scene.order}</strong>{assets.map((asset) => <p key={asset.id}><b>{asset.required ? "Required" : "Optional"} · {asset.kind}</b> {asset.description} <small>{asset.orientation}{asset.minimumResolution ? ` · ${asset.minimumResolution}` : ""} · {asset.rightsReminder}</small></p>)}</div>)}</section>
    </main></div>}{deleting && <DeleteDialog pkg={deleting} onClose={() => setDeleting(null)} onConfirm={() => void remove()} />}</section>;
}
