// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
const { invoke, open } = vi.hoisted(() => ({ invoke: vi.fn(), open: vi.fn() }));
vi.mock("@tauri-apps/api/core", () => ({ invoke }));
vi.mock("@tauri-apps/api/event", () => ({ listen: vi.fn().mockResolvedValue(() => {}) }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open }));
import DocumentaryView from "./DocumentaryView";
afterEach(() => { cleanup(); invoke.mockReset(); open.mockReset(); });
describe("DocumentaryView", () => {
  it("rejects an empty brief", async () => { invoke.mockResolvedValueOnce({ packages: [], warnings: [] }).mockResolvedValueOnce({ runs: [], warnings: [] }); render(<DocumentaryView />); await screen.findByText("No production packages yet"); fireEvent.click(screen.getByRole("button", { name: "Create package" })); expect(screen.getByRole("alert")).toHaveTextContent("Enter a topic."); expect(invoke).not.toHaveBeenCalledWith("create_documentary_package", expect.anything()); });
  it("prefills and attaches explicitly handed-off research after creation", async () => { const pkg = { version: 1, id: "one", topic: "Question", language: "English", audience: "", durationSeconds: 45, state: "brief", sources: [], scenes: [] }; invoke.mockResolvedValueOnce({ warnings: [], packages: [] }).mockResolvedValueOnce({ warnings: [], runs: [] }).mockResolvedValueOnce(pkg).mockResolvedValueOnce(pkg).mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs: [] }); render(<DocumentaryView handoffResearchRunId="run-1" handoffResearchQuery="Question" />); const topic = await screen.findByLabelText("Topic"); await vi.waitFor(() => expect(topic).toHaveValue("Question")); fireEvent.change(screen.getByLabelText("Audience"), { target: { value: "All" } }); fireEvent.click(screen.getByRole("button", { name: "Create package" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("attach_documentary_research", { packageId: "one", researchRunId: "run-1" })); });
  it("renders source approval and warns for uncertain claims", async () => { invoke.mockResolvedValueOnce({ warnings: [], packages: [{ version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "editing", sources: [{ id: "s", url: "https://example.com", canonicalUrl: "https://example.com", title: "Evidence", cited: true, approved: true }], script: { title: "", hook: "", narration: "", claims: [{ id: "c", text: "Interpretation", sourceIds: [], status: "uncertain" }] }, scenes: [] }] }).mockResolvedValueOnce({ runs: [], warnings: [] }); render(<DocumentaryView />); expect(await screen.findByRole("link", { name: "Evidence" })).toHaveAttribute("target", "_blank"); expect(screen.getByText("Needs human verification.")).toBeInTheDocument(); });
  it("starts inline research", async () => { const pkg = { version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "brief", sources: [], scenes: [] }; invoke.mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs: [] }).mockResolvedValueOnce({ id: "run-1" }).mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs: [] }); render(<DocumentaryView />); fireEvent.change(await screen.findByLabelText("Research question"), { target: { value: "Research story" } }); fireEvent.click(screen.getByRole("button", { name: "Start research" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("start_deep_research", { input: { query: "Research story", model: null, provider: null, thinking: null, originChatId: null, originSessionId: null, documentaryPackageId: "one" } })); });
  it("explains when another research run blocks launch", async () => { const pkg = { version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "brief", sources: [], scenes: [] }; const runs = [{ id: "global", query: "Global research", state: "running", documentary_package_id: "two", progress: { phase: "searching", activity: "Finding sources", searches: 1, reads: 0, checks: 0, active_calls: [] }, sources: [] }, { id: "other", query: "Other package", state: "completed", documentary_package_id: "two", final_report: "# Report", sources: [{ url: "https://example.com", canonical_url: "https://example.com", title: "Evidence", cited: true }] }, { id: "run-1", query: "Research story", state: "completed", documentary_package_id: "one", final_report: "# Report", sources: [{ url: "https://example.com", canonical_url: "https://example.com", title: "Evidence", cited: true }] }]; invoke.mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs }).mockResolvedValueOnce(pkg).mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs }); render(<DocumentaryView />); expect(await screen.findByText("Research story")).toBeInTheDocument(); expect(screen.getByText("Another research run is active. It blocks launch until it finishes.")).toHaveClass("documentary-research-blocked"); expect(screen.getByRole("button", { name: "Research blocked" })).toBeDisabled(); expect(screen.queryByText("Global research")).not.toBeInTheDocument(); expect(screen.queryByText("Other package")).not.toBeInTheDocument(); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("attach_documentary_research", { packageId: "one", researchRunId: "run-1" })); expect(invoke.mock.calls.filter(([command]) => command === "attach_documentary_research")).toHaveLength(1); });
  it("offers completed owned research without replacing attached sources", async () => { const pkg = { version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "reviewing_sources", researchRunId: "attached", sources: [{ id: "s", url: "https://attached.example", canonicalUrl: "https://attached.example", title: "Attached", cited: true, approved: false }], scenes: [] }; invoke.mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs: [{ id: "other", query: "Other research", state: "completed", documentary_package_id: "one", final_report: "# Report", sources: [{ url: "https://example.com", canonical_url: "https://example.com", title: "Evidence", cited: true }] }] }); render(<DocumentaryView />); expect(await screen.findByRole("button", { name: "Use this research" })).toBeDisabled(); expect(screen.getByText("Existing attached research is preserved.")).toBeInTheDocument(); expect(invoke).not.toHaveBeenCalledWith("attach_documentary_research", expect.anything()); });
  it("shows the live research card for the current package", async () => { const pkg = { version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "brief", sources: [], scenes: [] }; invoke.mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs: [{ id: "run-1", query: "Research story", state: "running", documentary_package_id: "one", progress: { phase: "reading", activity: "Reviewing evidence", searches: 2, reads: 3, checks: 1, active_calls: ["web_search", "fetch_content"] }, sources: [] }] }); render(<DocumentaryView />); const card = await screen.findByText("Research story"); expect(card.closest("article")).toHaveAttribute("aria-live", "polite"); expect(screen.getByText("Reviewing evidence")).toBeInTheDocument(); expect(screen.getByLabelText("Active tools")).toHaveTextContent("web_search"); expect(screen.getByLabelText("Active tools")).toHaveTextContent("fetch_content"); expect(screen.getByText("Searches").parentElement).toHaveTextContent("2"); expect(screen.getByText("Reads").parentElement).toHaveTextContent("3"); expect(screen.getByText("Checks").parentElement).toHaveTextContent("1"); const timeline = screen.getByLabelText("Research progress"); expect(timeline).toHaveTextContent("Preparing"); expect(timeline).toHaveTextContent("Searching web"); expect(timeline).toHaveTextContent("Reading sources"); expect(screen.getByText("Reading sources").closest("li")).toHaveAttribute("aria-current", "step"); expect(screen.getByText("Preparing").closest("li")).toHaveClass("complete"); expect(screen.getByRole("status")).toHaveTextContent("Research is active for this package."); expect(screen.getByRole("button", { name: "Research active" })).toBeDisabled(); });
  it("exports through the native directory chooser", async () => { const pkg = { version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "brief", sources: [], scenes: [] }; invoke.mockResolvedValueOnce({ warnings: [], packages: [pkg] }).mockResolvedValueOnce({ warnings: [], runs: [] }).mockResolvedValueOnce("/tmp/one"); open.mockResolvedValue("/tmp"); render(<DocumentaryView />); fireEvent.click(await screen.findByRole("button", { name: "Export package" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("export_documentary_package", { packageId: "one", directory: "/tmp" })); expect(await screen.findByText("Exported package to /tmp/one")).toHaveAttribute("role", "status"); });
});
