// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
const { invoke, open } = vi.hoisted(() => ({ invoke: vi.fn(), open: vi.fn() }));
vi.mock("@tauri-apps/api/core", () => ({ invoke }));
vi.mock("@tauri-apps/api/event", () => ({ listen: vi.fn().mockResolvedValue(() => {}) }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open }));
import DocumentaryView from "./DocumentaryView";

const pkg = (sources = [] as object[]) => ({ version: 1, id: "one", topic: "Story", language: "English", audience: "All", durationSeconds: 30, state: "brief", sources, scenes: [] });
function mockPackage(current = pkg()) { invoke.mockResolvedValueOnce({ warnings: [], packages: [current] }); }

afterEach(() => { cleanup(); invoke.mockReset(); open.mockReset(); });
describe("DocumentaryView", () => {
  it("rejects an empty brief", async () => { invoke.mockResolvedValueOnce({ packages: [], warnings: [] }); render(<DocumentaryView />); await screen.findByText("No production packages yet"); fireEvent.click(screen.getByRole("button", { name: "Create package" })); expect(screen.getByRole("alert")).toHaveTextContent("Enter a topic."); });
  it("prefills and attaches explicitly handed-off research after creation", async () => { const current = pkg(); invoke.mockResolvedValueOnce({ warnings: [], packages: [] }).mockResolvedValueOnce(current).mockResolvedValueOnce(current).mockResolvedValueOnce({ warnings: [], packages: [current] }); render(<DocumentaryView handoffResearchRunId="run-1" handoffResearchQuery="Question" />); const topic = await screen.findByLabelText("Topic"); await vi.waitFor(() => expect(topic).toHaveValue("Question")); fireEvent.change(screen.getByLabelText("Audience"), { target: { value: "All" } }); fireEvent.click(screen.getByRole("button", { name: "Create package" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("attach_documentary_research", { packageId: "one", researchRunId: "run-1" })); });
  it("approves all attached sources sequentially and clears approvals", async () => { const current = { ...pkg([{ id: "a", url: "https://a.example", canonicalUrl: "https://a.example", title: "A", cited: true, approved: false }, { id: "b", url: "https://b.example", canonicalUrl: "https://b.example", title: "B", cited: false, approved: true }]), researchRunId: "run-1" }; invoke.mockImplementation((command) => Promise.resolve(command === "list_documentary_packages" ? { warnings: [], packages: [current] } : undefined)); render(<DocumentaryView />); await screen.findByText("A"); fireEvent.click(screen.getByRole("button", { name: "Approve all" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("approve_documentary_source", { packageId: "one", sourceId: "a", approved: true })); await vi.waitFor(() => expect(screen.getByRole("button", { name: "Clear approvals" })).toBeEnabled()); fireEvent.click(screen.getByRole("button", { name: "Clear approvals" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("approve_documentary_source", { packageId: "one", sourceId: "b", approved: false })); });
  it("hides research composer and lists for attached research", async () => { const current = { ...pkg([{ id: "s", url: "https://example.com", canonicalUrl: "https://example.com", title: "Evidence", cited: true, approved: true }]), researchRunId: "run-1" }; mockPackage(current); render(<DocumentaryView />); await screen.findByText("Evidence"); expect(screen.queryByLabelText("Research question")).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Start research" })).not.toBeInTheDocument(); });
  it("directs packages without research to Deep Research", async () => { const onOpenDeepResearch = vi.fn(); mockPackage(); render(<DocumentaryView onOpenDeepResearch={onOpenDeepResearch} />); fireEvent.click(await screen.findByRole("button", { name: "Open Deep Research" })); expect(onOpenDeepResearch).toHaveBeenCalledOnce(); expect(screen.queryByLabelText("Research question")).not.toBeInTheDocument(); });
  it("exports through the native directory chooser", async () => { mockPackage(); invoke.mockResolvedValueOnce({ warnings: [], packages: [pkg()] }).mockResolvedValueOnce("/tmp/one"); open.mockResolvedValue("/tmp"); render(<DocumentaryView />); fireEvent.click(await screen.findByRole("button", { name: "Export package" })); await vi.waitFor(() => expect(invoke).toHaveBeenCalledWith("export_documentary_package", { packageId: "one", directory: "/tmp" })); });
});
